services:
  auth-postgres:
    container_name: auth-postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: 'local-user'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-redis:
    container_name: auth-redis
    image: redis:8.0-rc1-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  auth-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: auth-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  auth-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: auth-kafka
    depends_on:
      - auth-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: auth-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://auth-kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  auth-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: auth-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: auth-kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - auth-kafka

volumes:
  postgres_data:
  redis_data: