services:
  auth-postgres:
    container_name: auth-postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: 'local-user'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-redis:
    container_name: auth-redis
    image: redis:8.0-rc1-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: