services:
  auth-postgres:
    container_name: auth-postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: 'ci-user'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'

  auth-redis:
    container_name: auth-redis
    image: redis:8.0-rc1-alpine
    ports:
      - '6379:6379'

  auth-service:
    container_name: auth-service
    build:
      context: ../..
      dockerfile: ./docker/ecs/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    environment:
      SPRING_PROFILES_ACTIVE: 'ci'
    ports:
      - '8181:8181'
    depends_on:
      - auth-postgres
      - auth-redis