
name: Verify the

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run build environment
        run: cd docker/local && ./pull.sh && ./env.sh

      - name: Clear project
        run: mvn clean

      - name: Compile the project
        run: mvn compile

      - name: Run tests
        run: mvn test